# Generated by Django 4.2 on 2024-04-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='is_favorite',
        ),
    ]
