# Generated by Django 4.2 on 2024-04-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_favorite_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'complete')], default='2', max_length=1),
        ),
    ]
